[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AUTOHIAM"
authors = [{name = "shengyangzhuang", email = "shengyangzhuang@outlook.com"}]
dynamic = ["version", "description"]
